---
apiVersion: v1
kind: Service
metadata:
  name: cornerstone-issuer-agent
  namespace: cornerstone-issuer
spec:
  type: ClusterIP         # Default type (ClusterIP), NodePort, LoadBalancer
  selector:
    app: cornerstone-issuer-agent
  ports:
    - name: admin-port
      port: 8001          #service port http
      targetPort: 8001
      protocol: TCP
    - name: http-port
      port: 8000          #service port http
      targetPort: 8000 
      protocol: TCP


# kubectl port-forward service/cornerstone-issuer-agent 8180:8180 -n cornerstone-issuer
# kubectl port-forward deployment.apps/cornerstone-issuer-agent 8180:8180 -n cornerstone-issuer

# localhost:8180/ 

