version: "3.4"

services:
  cornerstone_issuer:
    image: cornerstone_issuer
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8180:8180
    environment:
      ACAPY_URL: "http://0.0.0.0:8001"
      CLIENT_URL: "http://localhost:3000"
      SERVER_HOST: "0.0.0.0:8180"
      API_BASE_URL: "/api/v1"

  cornerstone_issuer_agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.3
    container_name: issuer-agent
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://issuer-agent:8000"
      ACAPY_LABEL: "Cornerstone Issuer"
      ACAPY_GENESIS_URL: "http://172.20.0.1:9000/genesis"
      ACAPY_WALLET_NAME: "issuer_wallet"
      ACAPY_WALLET_KEY: "issuer_secret"
      ACAPY_WALLET_TYPE: "indy"
      ACAPY_WALLET_SEED: "Issuer00000000000000000000000000"
      ACAPY_LOG_LEVEL: "info"
      ADMIN_PORT: "8001"
      AGENT_PORT: "8000"
    entrypoint: /bin/bash
    command: [
        "-c",
        "aca-py start \
        --admin '0.0.0.0' 8001 \
        --inbound-transport http '0.0.0.0' 8000 \
        --outbound-transport http ",
      ]
    ports:
      - "8001:8001"
